on: [pull_request]

name: validate-schema-changes
jobs:
  validate-and-detect-breaking-changes: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out HEAD rev
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: head
    - name: Check out BASE rev
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        path: base
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Npm install
      working-directory: base
      run: npm install    

    - name: Npm test
      working-directory: base
      run: |
        cat openapi/openapi.yaml
        npm test

    - name: Run OpenAPI Diff (from HEAD rev)
      uses: docker://openapitools/openapi-diff:latest 
      with:
        args: --fail-on-incompatible head/openapi.yaml base/openapi.yaml